-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Kysymys CASCADE;
DROP TABLE IF EXISTS Vastaus CASCADE;
DROP TABLE IF EXISTS Käyttäjä CASCADE;
DROP TABLE IF EXISTS Kyselylomake CASCADE;
DROP TABLE IF EXISTS LiitosLomakeKysymys CASCADE;
DROP TABLE IF EXISTS Kurssi CASCADE;
DROP TABLE IF EXISTS LiitosKäyttäjäKurssi CASCADE;
DROP TABLE IF EXISTS YksityiskohtainenRaportti CASCADE;